export { CopilotChat } from './CopilotChat'
export { useCopilotChat } from './useCopilotChat'
export { copilotSkills, matchSkill } from './skills/registry'
export type { CopilotSkill, CopilotTool } from './skills/types'
export { matchBot, successorsOf, useCopilotBots, copilotBotsQueryKey } from './bots/registry'
export type { CopilotBot } from './bots/registry'
