#!/usr/bin/env python3
"""Generate one QM/LSF runbook per registered model-plugin key."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent
REPO = ROOT.parents[1]
REGISTRY = ROOT / "registry.json"
NOTICE = (
    "<!-- Generated by qm-scripts/plugins/generate_docs.py; edit registry.json. -->"
)


def load_registry() -> dict[str, Any]:
    return json.loads(REGISTRY.read_text())


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_plugin(profile: dict[str, Any], catalog: dict[str, Any]) -> str:
    key = profile["plugin_key"]
    lines = [
        NOTICE,
        f"# {key}: QM cluster runbook",
        "",
        f"> Inventory date: {catalog['inventory_date']} · Cluster: {catalog['cluster']}",
        "",
        "This page records how this plugin is written for the SUSTech QM cluster and what has actually run. "
        "A historical row is not current runtime proof unless its evidence fingerprint matches the current ModelPlugin declaration.",
        "",
        "## Registry and runtime",
        "",
        f"- Documented versions: `{', '.join(profile['versions'])}`",
        f"- Submission state: `{profile['state']}`",
        f"- Direct submission authorized: `{'yes' if profile['submission_authorized'] else 'no'}`",
        f"- Runtime: {profile['runtime']}",
        f"- LSF resources: {profile['resources']}",
        f"- Site-wide rules: [`{catalog['operation_rules']}`](../../../{catalog['operation_rules']})",
        "- At submission time, the selected ModelPlugin snapshot remains authoritative for the exact command, ports, runtime setup and resources.",
        "",
        "## How to write and review the job",
        "",
    ]
    if not profile["submission_authorized"]:
        lines.extend(
            [
                "Direct submission is not authorized for this profile. Do not submit an LSF script until its installation, declaration and site configuration are validated.",
                "The configuration path below is documentation only.",
                "",
            ]
        )
    if profile["renderer"] == "qm_job":
        model = profile["qm_job_model"]
        lines.extend(
            [
                (
                    "Use the reviewed hand-submission library when a workflow dispatch is not appropriate:"
                    if profile["submission_authorized"]
                    else "The hand-submission library may be used to inspect the current template, but not to submit it:"
                ),
                "",
                "```bash",
                f"python qm-scripts/library/qm_job.py params {model}",
                f"python qm-scripts/library/qm_job.py validate <config-for-{profile['slug']}.json>",
                f"python qm-scripts/library/qm_job.py render <config-for-{profile['slug']}.json> --output <job-dir>",
                "bash -n <job-dir>/submit.lsf",
                "```",
                "",
            ]
        )
        if profile.get("example"):
            example = profile["example"]
            lines.append(f"Starting example: [`{example}`](../../../{example})")
            lines.append("")
        else:
            lines.append(
                "No committed example config exists yet; start from `qm_job.py params` and keep the first run minimal."
            )
            lines.append("")
    else:
        lines.extend(
            [
                "Use the platform renderer: bind the exact registry plugin version to a workflow node, fill canonical inputs, "
                "open the LSF preview, and review `#BSUB`, staging directories, runtime setup and the final command before submission.",
                "This plugin intentionally has no second hand-written command catalog; the ModelPlugin snapshot is the command source.",
                "",
            ]
        )
    lines.extend(["Plugin-specific checks:", ""])
    lines.extend(f"- {rule}" for rule in profile["rules"])
    lines.extend(
        [
            "",
            (
                "The authorized submission order is `validate → render/preview → review → stage → review → bsub`. "
                "Queue selection is made from a current `bqueues` check; do not copy another job's queue or CPU count."
                if profile["submission_authorized"]
                else "Stop after template review. The `stage` and `bsub` steps remain prohibited until this profile is authorized."
            ),
            "",
        ]
    )
    lines.extend(["## Recorded cluster observations", ""])
    observations = profile.get("observations", [])
    if not observations:
        lines.extend(
            [
                "No source-backed QM execution is recorded for this plugin declaration. Installation or schema presence must not be described as a successful run.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "| Observed | Completed | LSF job(s) | Result | What was checked | Scope | Evidence |",
                "|---|---|---|---|---|---|---|",
            ]
        )
        for item in observations:
            jobs = ", ".join(item["job_ids"]) or "not recorded"
            sources = "<br>".join(
                f"[`{source}`](../../../{source})" for source in item["sources"]
            )
            lines.append(
                "| "
                + " | ".join(
                    _cell(value)
                    for value in (
                        item["observed_on"],
                        item.get("completed_on", "—"),
                        jobs,
                        item["result"],
                        item["summary"],
                        item["proof_scope"],
                        sources,
                    )
                )
                + " |"
            )
        lines.append("")
    lines.extend(
        [
            "## Updating this record",
            "",
            "After a real run, add its date, job ID, terminal/scientific result and immutable evidence source to "
            "`qm-scripts/plugins/registry.json`, then run:",
            "",
            "```bash",
            "python qm-scripts/plugins/generate_docs.py --write",
            "python qm-scripts/plugins/generate_docs.py --check",
            "```",
            "",
            "Only use `record_plugin_runtime_validation.py --proven` after checking parameter acknowledgement and declared outputs, "
            "because that operation attaches the current declaration fingerprint.",
            "",
        ]
    )
    return "\n".join(lines)


def render_index(catalog: dict[str, Any]) -> str:
    lines = [
        NOTICE,
        "# QM plugin cluster runbooks",
        "",
        "Every registered model-plugin key has one runbook below. These pages complement the executable ModelPlugin declaration: "
        "the declaration renders the job, while the runbook explains the SUSTech LSF rules and preserves dated observations.",
        "",
        f"Inventory date: `{catalog['inventory_date']}` · cluster: `{catalog['cluster']}` · "
        f"site policy: [`{catalog['operation_rules']}`](../../{catalog['operation_rules']})",
        "",
        "| Plugin | Versions | State | Renderer | Last recorded observation |",
        "|---|---|---|---|---|",
    ]
    for profile in sorted(
        catalog["plugins"], key=lambda item: item["plugin_key"].lower()
    ):
        observations = profile.get("observations", [])
        last = max(
            (item.get("completed_on") or item["observed_on"] for item in observations),
            default="none",
        )
        lines.append(
            f"| [{profile['plugin_key']}](./{profile['slug']}/README.md) | "
            f"{', '.join(profile['versions'])} | {profile['state']} "
            f"({'submit' if profile['submission_authorized'] else 'review only'}) | {profile['renderer']} | {last} |"
        )
    lines.extend(
        [
            "",
            "`historical_observation` means the tool ran under a recorded declaration or hand script. It does not bypass the "
            "registry's fingerprint check after commands, ports, resources, environment or output contracts change.",
            "",
        ]
    )
    return "\n".join(lines)


def expected_files(catalog: dict[str, Any]) -> dict[Path, str]:
    result = {ROOT / "README.md": render_index(catalog)}
    result.update(
        {
            ROOT / profile["slug"] / "README.md": render_plugin(profile, catalog)
            for profile in catalog["plugins"]
        }
    )
    return result


def check(files: dict[Path, str]) -> int:
    stale = [
        path
        for path, content in files.items()
        if not path.exists() or path.read_text() != content
    ]
    if stale:
        for path in stale:
            print(f"[stale] {path.relative_to(REPO)}")
        return 1
    print(f"[OK] {len(files) - 1} plugin runbooks and index are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = expected_files(load_registry())
    if args.write:
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print(f"[OK] wrote {len(files) - 1} plugin runbooks and index")
        return 0
    return check(files)


if __name__ == "__main__":
    raise SystemExit(main())
