"""Codon usage per expression host, counted from annotated genomes.

Generated by `backend_v2/scripts/build_codon_usage.py` - do not edit by hand.
Re-run that script to add a host or move to a newer assembly.

Each entry carries the accessions it was counted from and how many coding
sequences survived the filters, because a codon weight is only as good as the
number of genes behind it. Counts are raw occurrences; the relative
adaptiveness a CAI needs is derived in `app/sequences/codon.py`, so the data
here stays the measurement and the weighting stays a decision.

Retrieved from EBI/ENA on 2026-09-15.
"""

from __future__ import annotations

from typing import Any

#: Keyed by host id. Counts exclude the terminal stop codon; see the generator.
CODON_USAGE: dict[str, dict[str, Any]] = {
    'ecoli_k12': {
        'label': 'Escherichia coli K-12 MG1655',
        'organism': 'Escherichia coli str. K-12 substr. MG1655',
        'taxon_id': 511145,
        'translation_table': 11,
        'note': 'The standard laboratory K-12 genome; one circular record carrying every CDS.',
        'accessions': ['U00096'],
        'cds_counted': 4297,
        'cds_rejected': {'ambiguous': 0, 'internal_stop': 3, 'not_a_triplet': 0, 'partial_or_pseudo': 18},
        'codons_counted': 1327310,
        'counts': {
            'AAA': 44833, 'AAC': 28602, 'AAG': 13593, 'AAT': 23136,
            'ACA': 9139, 'ACC': 31245, 'ACG': 19131, 'ACT': 11742,
            'AGA': 2594, 'AGC': 21362, 'AGG': 1438, 'AGT': 11518,
            'ATA': 5522, 'ATC': 33661, 'ATG': 37166, 'ATT': 40648,
            'CAA': 20479, 'CAC': 12943, 'CAG': 38594, 'CAT': 17145,
            'CCA': 11196, 'CCC': 7255, 'CCG': 31188, 'CCT': 9264,
            'CGA': 4646, 'CGC': 29528, 'CGG': 7107, 'CGT': 28181,
            'CTA': 5175, 'CTC': 14879, 'CTG': 70967, 'CTT': 14643,
            'GAA': 52980, 'GAC': 25475, 'GAG': 23752, 'GAT': 42600,
            'GCA': 26850, 'GCC': 34228, 'GCG': 45274, 'GCT': 20281,
            'GGA': 10388, 'GGC': 39681, 'GGG': 14617, 'GGT': 32916,
            'GTA': 14510, 'GTC': 20409, 'GTG': 35144, 'GTT': 24351,
            'TAC': 16210, 'TAT': 21316, 'TCA': 9355, 'TCC': 11445,
            'TCG': 11869, 'TCT': 11181, 'TGC': 8600, 'TGG': 20231,
            'TGT': 6829, 'TTA': 18380, 'TTC': 22044, 'TTG': 18217,
            'TTT': 29657,
        },
    },
    'scerevisiae_s288c': {
        'label': 'Saccharomyces cerevisiae S288C',
        'organism': 'Saccharomyces cerevisiae S288C',
        'taxon_id': 559292,
        'translation_table': 1,
        'note': 'Sixteen nuclear chromosomes. Mitochondrial DNA excluded: different genetic code.',
        'accessions': ['BK006935', 'BK006936', 'BK006937', 'BK006938', 'BK006939', 'BK006940', 'BK006941', 'BK006942', 'BK006943', 'BK006944', 'BK006945', 'BK006946', 'BK006947', 'BK006948', 'BK006949', 'BK006934'],
        'cds_counted': 6002,
        'cds_rejected': {'ambiguous': 0, 'internal_stop': 0, 'not_a_triplet': 0, 'partial_or_pseudo': 6},
        'codons_counted': 2925240,
        'counts': {
            'AAA': 125485, 'AAC': 72614, 'AAG': 89308, 'AAT': 107159,
            'ACA': 53271, 'ACC': 36562, 'ACG': 23918, 'ACT': 59273,
            'AGA': 61628, 'AGC': 29229, 'AGG': 27721, 'AGT': 42788,
            'ATA': 53709, 'ATC': 49761, 'ATG': 60682, 'ATT': 88201,
            'CAA': 79311, 'CAC': 22736, 'CAG': 36387, 'CAT': 40744,
            'CCA': 52142, 'CCC': 20288, 'CCG': 15931, 'CCT': 39772,
            'CGA': 9144, 'CGC': 7776, 'CGG': 5401, 'CGT': 18407,
            'CTA': 39619, 'CTC': 16266, 'CTG': 31254, 'CTT': 36150,
            'GAA': 133989, 'GAC': 59661, 'GAG': 57240, 'GAT': 111378,
            'GCA': 47688, 'GCC': 35588, 'GCG': 18139, 'GCT': 59377,
            'GGA': 32818, 'GGC': 28708, 'GGG': 17784, 'GGT': 66076,
            'GTA': 35394, 'GTC': 32900, 'GTG': 31451, 'GTT': 62867,
            'TAC': 42794, 'TAT': 55921, 'TCA': 55852, 'TCC': 41235,
            'TCG': 25551, 'TCT': 68431, 'TGC': 14055, 'TGG': 30379,
            'TGT': 23035, 'TTA': 77137, 'TTC': 52531, 'TTG': 77594,
            'TTT': 77030,
        },
    },
}
