import type { Icon } from '@phosphor-icons/react'
import { ChartBar, BookOpen, Cube, ClipboardText, Cpu, Crosshair, Database, Flask, Package, SlidersHorizontal, Sparkle } from '@phosphor-icons/react'

export interface WorkflowStationData {
  id: string
  stepNumber: number
  title: string
  stationLabel: string
  beginnerExplanation: string
  technicalDetail: string
  inputs: string[]
  outputs: string[]
  commonFailures: string[]
  userDecisions: string[]
  icon: Icon
}

export const GUIDE_WORKFLOW_STATIONS: WorkflowStationData[] = [
  {
    id: "research",
    stepNumber: 1,
    title: "Research & Literature Review",
    beginnerExplanation: "Collect sources for the research question and record what they support. With a configured model, a bot can help draft the review.",
    technicalDetail: "Search literature and target records, open the cited sources, and distinguish metadata, abstracts and full-text evidence.",
    inputs: ["Research question or target name", "Optional papers or database IDs"],
    outputs: ["Review notes with source links", "Open questions and conflicting evidence"],
    commonFailures: ["Claims without supporting sources", "Treating an abstract as a full-paper review"],
    userDecisions: ["Accept or revise findings", "Record unresolved evidence"],
    stationLabel: "Research & Literature Review",
    icon: BookOpen,
  },
  {
    id: "target-confirmation",
    stepNumber: 2,
    title: "Target Protein Confirmation",
    beginnerExplanation: "Check the intended protein, species and construct before using its sequence or structure.",
    technicalDetail: "Compare available target records and their sources. Confirm accession, isoform and residue range; the number of options depends on the search.",
    inputs: ["Target name, gene or UniProt ID", "Species and construct requirements"],
    outputs: ["Reviewed target identity", "Source records and remaining uncertainties"],
    commonFailures: ["Ambiguous gene name or species", "Mismatched isoform or construct range"],
    userDecisions: ["Choose the intended target", "Confirm species, isoform and residue range"],
    stationLabel: "Target Protein Confirmation",
    icon: Crosshair,
  },
  {
    id: "pdb-download",
    stepNumber: 3,
    title: "PDB / Structure Download",
    beginnerExplanation: "Search for structures and compare their source, chains and coverage before choosing an input.",
    technicalDetail: "Import a selected PDB record or upload a PDB/mmCIF file. Check available method and resolution metadata. Record when an input is predicted rather than experimental.",
    inputs: ["Confirmed target identity", "Available structure IDs or files"],
    outputs: ["Imported structure artifact", "Source and structure metadata"],
    commonFailures: ["Wrong species, chain or construct", "Missing or unsuitable structure file"],
    userDecisions: ["Choose a suitable structure", "Check chain selection and prediction status"],
    stationLabel: "PDB / Structure Download",
    icon: Database,
  },
  {
    id: "structure-cleaning",
    stepNumber: 4,
    title: "Structure Cleaning & Preparation",
    beginnerExplanation: "Review chains, ligands and missing regions, then prepare and inspect the structure you intend to use.",
    technicalDetail: "Preparation can filter chains, waters and heteroatoms in PDB files. mmCIF content is currently retained unchanged. Missing residues and loops are not rebuilt automatically.",
    inputs: ["Source structure artifact", "Chains and ligands to retain"],
    outputs: ["Prepared artifact linked to its source", "Structure revision for review"],
    commonFailures: ["Missing regions affect the design site", "Required chains or ligands removed"],
    userDecisions: ["Inspect the prepared file before approval", "Handle missing regions separately or choose another structure"],
    stationLabel: "Structure Cleaning & Preparation",
    icon: Flask,
  },
  {
    id: "design-goal",
    stepNumber: 5,
    title: "Design Goal Selection",
    beginnerExplanation: "Record the design goal and how you will evaluate it, including any required experiments.",
    technicalDetail: "Separate desired properties from metrics the available tools can measure. Set priorities and thresholds explicitly before configuring the workflow.",
    inputs: ["Research goal and constraints", "Available inputs and evaluation methods"],
    outputs: ["Written objective and success criteria", "Chosen metrics and thresholds"],
    commonFailures: ["Conflicting or vague objectives", "No available method to evaluate a goal"],
    userDecisions: ["Confirm priorities", "Choose computational checks and experimental follow-up"],
    stationLabel: "Design Goal Selection",
    icon: SlidersHorizontal,
  },
  {
    id: "agent-planning",
    stepNumber: 6,
    title: "Workflow Planning",
    beginnerExplanation: "Choose a route, build a workflow, or ask a configured bot for a draft. Review the proposed steps before execution.",
    technicalDetail: "Check enabled plugins, bind input artifacts, set parameters and configure connection gates. A proposed route still needs valid inputs and a ready execution environment.",
    inputs: ["Goal and evaluation criteria", "Input artifacts and available plugins"],
    outputs: ["Editable workflow draft", "Parameters, connections and input bindings"],
    commonFailures: ["Required inputs or plugins unavailable", "Unconfigured gates or invalid parameters"],
    userDecisions: ["Review and revise the draft", "Resolve preflight blockers"],
    stationLabel: "Workflow Planning",
    icon: ClipboardText,
  },
  {
    id: "model-execution",
    stepNumber: 7,
    title: "Model Execution",
    beginnerExplanation: "Run preflight, review each script and confirm submission to the configured execution site. Track tasks and collected outputs.",
    technicalDetail: "Docker or LSF execution depends on the site configuration. Demo mode only simulates status and produces no model output. Submitted runs retain their input and parameter snapshots.",
    inputs: ["Reviewed workflow and scripts", "Bound input artifacts", "Configured compute resources"],
    outputs: ["Task status and logs", "Collected outputs when the job produces them"],
    commonFailures: ["Unavailable runtime or queue", "Job failure or missing output", "Inputs changed after preview"],
    userDecisions: ["Confirm submission after review", "Inspect failures before a new attempt", "Cancel work when appropriate"],
    stationLabel: "Model Execution",
    icon: Cpu,
  },
  {
    id: "candidate-generation",
    stepNumber: 8,
    title: "Candidate Generation",
    beginnerExplanation: "Check whether the completed job produced usable sequences or structures, then review the available candidates.",
    technicalDetail: "Output collection stores files as artifacts. Candidate records and metrics depend on the plugin output format and supported parser; a successful task may have no candidate records.",
    inputs: ["Generation task outputs", "Plugin output specification"],
    outputs: ["Available sequences or structures", "Candidate records when supported"],
    commonFailures: ["No output files or candidate records", "Low diversity or unsuitable structures"],
    userDecisions: ["Check artifacts and candidate provenance", "Adjust the plan if more designs are needed"],
    stationLabel: "Candidate Generation",
    icon: Sparkle,
  },
  {
    id: "scoring-ranking",
    stepNumber: 9,
    title: "Scoring & Ranking",
    beginnerExplanation: "Compare the metrics already recorded for candidates. Add a suitable scoring step when the needed measurements are missing.",
    technicalDetail: "Check each metric’s method, units and conditions. pLDDT, ipTM and energy scores answer different questions; the platform does not guarantee a shared score for every candidate.",
    inputs: ["Candidates and recorded metrics", "Evaluation criteria"],
    outputs: ["Filtered and sorted candidate table", "Evidence for candidate selection"],
    commonFailures: ["Missing metrics or incompatible conditions", "Relying on one score alone"],
    userDecisions: ["Choose relevant metrics and thresholds", "Decide which candidates need more evaluation"],
    stationLabel: "Scoring & Ranking",
    icon: ChartBar,
  },
  {
    id: "visualization",
    stepNumber: 10,
    title: "Visualization & Interpretation",
    beginnerExplanation: "Open an available structure in the 3D viewer and compare it with its sequence, scores and source.",
    technicalDetail: "Inspect chains and residue numbering in Mol*. Request further explanation from Copilot when a model is configured, and check its claims against recorded evidence.",
    inputs: ["Structure artifacts", "Associated metrics and source records"],
    outputs: ["3D structure view", "Review notes and next questions"],
    commonFailures: ["Missing or invalid structure file", "Treating a prediction as experimental evidence"],
    userDecisions: ["Select candidates for follow-up", "Record uncertainties and further checks"],
    stationLabel: "Visualization & Interpretation",
    icon: Cube,
  },
  {
    id: "export",
    stepNumber: 11,
    title: "Export & Experimental Planning",
    beginnerExplanation: "Export available candidate data and structures, then record experiments and results against the relevant candidates.",
    technicalDetail: "Candidates supports CSV and selected-structure downloads. Results provides existing artifacts and ready delivery packages. Plan further rounds from the reviewed evidence; they are not an automatic experimental loop.",
    inputs: ["Selected candidates and available artifacts", "Source records and experiment plan"],
    outputs: ["Exported files", "Linked experimental records"],
    commonFailures: ["Requested files are unavailable", "Partial results lack context or provenance"],
    userDecisions: ["Choose export scope and record omissions", "Review experiments before planning another round"],
    stationLabel: "Export & Experimental Planning",
    icon: Package,
  },
]

type StationCopy = Omit<WorkflowStationData, 'id' | 'stepNumber' | 'icon'>

const GUIDE_WORKFLOW_ZH: Record<string, StationCopy> = {
  "research": {
    title: "研究与文献综述",
    beginnerExplanation: "围绕研究问题收集来源，记录证据支持什么。配置模型后，可让 Bot 协助起草综述。",
    technicalDetail: "检索文献和靶点记录，打开引用来源，区分元数据、摘要与全文证据。",
    inputs: ["研究问题或靶点名称", "可选论文或数据库 ID"],
    outputs: ["带来源链接的综述笔记", "待解决问题与冲突证据"],
    commonFailures: ["结论缺少支持来源", "把摘要当成已阅读全文"],
    userDecisions: ["接受或修订发现", "记录尚未解决的证据问题"],
    stationLabel: "研究与文献综述",
  },
  "target-confirmation": {
    title: "靶点蛋白确认",
    beginnerExplanation: "使用序列或结构前，核对目标蛋白、物种和构建范围。",
    technicalDetail: "比较可用靶点记录及其来源，确认登录号、亚型与残基范围；候选数量取决于检索结果。",
    inputs: ["靶点名称、基因或 UniProt ID", "物种与构建要求"],
    outputs: ["已核对的靶点身份", "来源记录与未确定信息"],
    commonFailures: ["基因名称或物种含糊", "亚型或构建范围不匹配"],
    userDecisions: ["选择目标靶点", "确认物种、亚型和残基范围"],
    stationLabel: "靶点蛋白确认",
  },
  "pdb-download": {
    title: "PDB / 结构下载",
    beginnerExplanation: "检索结构，比较来源、链和覆盖范围后再选择输入。",
    technicalDetail: "导入选定的 PDB 记录或上传 PDB/mmCIF 文件，核对可用的实验方法和分辨率信息。预测结构需保留预测标识。",
    inputs: ["已确认靶点", "可用结构 ID 或文件"],
    outputs: ["导入的结构制品", "来源与结构元数据"],
    commonFailures: ["物种、链或构建不符", "文件缺失或结构不适用"],
    userDecisions: ["选择合适结构", "核对链和预测标识"],
    stationLabel: "PDB / 结构下载",
  },
  "structure-cleaning": {
    title: "结构清理与准备",
    beginnerExplanation: "检查链、配体和缺失区域，准备结构后再核对实际内容。",
    technicalDetail: "准备功能可筛选 PDB 文件中的链、水和异原子；mmCIF 目前保留原内容。缺失残基和环区不会自动补建。",
    inputs: ["原始结构制品", "需要保留的链和配体"],
    outputs: ["关联原始来源的准备后制品", "待审核的结构版本"],
    commonFailures: ["缺失区域影响设计位点", "误删所需链或配体"],
    userDecisions: ["检查准备后文件再批准", "单独处理缺失区域或换用其他结构"],
    stationLabel: "结构清理与准备",
  },
  "design-goal": {
    title: "设计目标选择",
    beginnerExplanation: "记录设计目标与评价方法，包括需要进行的实验。",
    technicalDetail: "区分期望性质与现有工具能测量的指标。在配置工作流前，明确优先级和阈值。",
    inputs: ["研究目标与约束", "可用输入与评价方法"],
    outputs: ["书面目标与成功标准", "选定指标和阈值"],
    commonFailures: ["目标冲突或含糊", "缺少评价目标的方法"],
    userDecisions: ["确认优先级", "选择计算检查和后续实验"],
    stationLabel: "设计目标选择",
  },
  "agent-planning": {
    title: "工作流规划",
    beginnerExplanation: "选择路线、手动建图，或请已配置的 Bot 起草方案。执行前检查各步骤。",
    technicalDetail: "核对已启用插件，绑定输入制品，设置参数和连接门控。建议路线仍需有效输入和可用运行环境。",
    inputs: ["目标与评价标准", "输入制品和可用插件"],
    outputs: ["可编辑工作流草稿", "参数、连接和输入绑定"],
    commonFailures: ["缺少必需输入或插件", "门控未配置或参数无效"],
    userDecisions: ["审阅并修改草稿", "解决预检阻塞项"],
    stationLabel: "工作流规划",
  },
  "model-execution": {
    title: "模型执行",
    beginnerExplanation: "完成预检，逐项检查脚本并确认提交到已配置的计算站点。随后查看任务与收集的输出。",
    technicalDetail: "Docker 或 LSF 执行依赖站点配置。演示模式只模拟状态，不生成模型输出。已提交运行保留输入和参数快照。",
    inputs: ["已审阅的工作流与脚本", "已绑定输入制品", "已配置计算资源"],
    outputs: ["任务状态与日志", "任务实际生成并收集的输出"],
    commonFailures: ["运行环境或队列不可用", "任务失败或输出缺失", "预览后输入发生变化"],
    userDecisions: ["审阅后确认提交", "检查失败原因再发起新尝试", "按需要取消任务"],
    stationLabel: "模型执行",
  },
  "candidate-generation": {
    title: "候选物生成",
    beginnerExplanation: "检查任务是否生成可用序列或结构，再查看已有候选物。",
    technicalDetail: "输出收集会把文件登记为制品。候选记录和指标取决于插件输出格式及解析器支持；任务成功不保证出现候选记录。",
    inputs: ["生成任务输出", "插件输出要求"],
    outputs: ["可用的序列或结构", "受支持输出对应的候选记录"],
    commonFailures: ["没有输出文件或候选记录", "多样性不足或结构不适用"],
    userDecisions: ["核对制品和候选来源", "需要更多设计时调整方案"],
    stationLabel: "候选物生成",
  },
  "scoring-ranking": {
    title: "评分与排序",
    beginnerExplanation: "比较候选物已有指标。缺少所需测量时，再配置合适的评分步骤。",
    technicalDetail: "核对指标的方法、单位和条件。pLDDT、ipTM 与能量评分含义不同，平台不保证每个候选都有统一总分。",
    inputs: ["候选物与已记录指标", "评价标准"],
    outputs: ["筛选和排序后的候选表", "选择候选的依据"],
    commonFailures: ["指标缺失或条件不可比", "仅依赖单项评分"],
    userDecisions: ["选择相关指标和阈值", "决定哪些候选需要进一步评价"],
    stationLabel: "评分与排序",
  },
  "visualization": {
    title: "可视化与解读",
    beginnerExplanation: "在三维查看器中打开可用结构，对照序列、评分和来源进行检查。",
    technicalDetail: "在 Mol* 中核对链与残基编号。配置模型后可请 Copilot 进一步解释，并用已有证据核查结论。",
    inputs: ["结构制品", "对应指标与来源记录"],
    outputs: ["三维结构视图", "检查笔记与后续问题"],
    commonFailures: ["结构文件缺失或无效", "把预测当作实验证据"],
    userDecisions: ["选择后续研究候选", "记录不确定性和补充检查"],
    stationLabel: "可视化与解读",
  },
  "export": {
    title: "导出与实验规划",
    beginnerExplanation: "导出已有候选数据和结构，再将实验与结果关联到对应候选。",
    technicalDetail: "候选页支持 CSV 和所选结构下载；结果页提供已有制品及准备好的交付包。根据审阅后的证据规划下一轮，不会自动完成实验闭环。",
    inputs: ["选定候选与可用制品", "来源记录和实验计划"],
    outputs: ["导出文件", "关联的实验记录"],
    commonFailures: ["所需文件不可用", "部分结果缺少背景或来源"],
    userDecisions: ["选择导出范围并注明缺失项", "审阅实验结果后规划下一轮"],
    stationLabel: "导出与实验规划",
  },
}

export function getGuideWorkflowStations(language: 'en' | 'zh'): WorkflowStationData[] {
  if (language === 'en') return GUIDE_WORKFLOW_STATIONS
  return GUIDE_WORKFLOW_STATIONS.map((station) => ({
    ...station,
    ...GUIDE_WORKFLOW_ZH[station.id],
  }))
}
